doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '%env(resolve:POSTGRES_VERSION)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            marketing_launch:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Marketing/Domain/Launch/Model'
                prefix: 'App\Marketing\Domain\Launch'
                alias: MarketingLaunch
            content_management_website:
                is_bundle: false
                dir: '%kernel.project_dir%/src/ContentManagement/Domain/Website/Model'
                prefix: 'App\ContentManagement\Domain\Website'
                alias: ContentManagementWebsite
            supporting_i18n:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Supporting/Domain/I18n/Model'
                prefix: 'App\Supporting\Domain\I18n'
                alias: SupportingI18n
            account_management_user:
                is_bundle: false
                dir: '%kernel.project_dir%/src/AccountManagement/Domain/User/Model'
                prefix: 'App\AccountManagement\Domain\User'
                alias: AccountManagementUser

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
