# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    
    # trust *all* requests (the 'REMOTE_ADDR' string is replaced at
    # run time by $_SERVER['REMOTE_ADDR'])
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    php_errors:
        log: true
    
    # When using the controller() function, controllers are not accessed 
    # using a regular Symfony route but through a special URL used exclusively
    # to serve those template fragments.
    fragments: { path: /_fragment }

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
