twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'web/shared/form/_mdbootstrap_layout.html.twig' ]
    globals:
        locales: "%supported_locales%"
        
when@test:
    twig:
        strict_variables: true
