kernel:
    resource: ../src/Kernel.php
    type: annotation
    
controllers:
    resource: '../src/**/Controller/*Controller.php'
    type: annotation
    prefix:
        en: '' # don't prefix URLs for English, the default locale
        fr: '/fr'
