name: Static analysis
on: [pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-20.04
    strategy:
        fail-fast: true
        matrix:
            php-versions: [ '8.1' ]
            
    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-versions }}
            coverage: none
            tools: phpstan:0.12.92, cs2pr
            
      -   name: Download dependencies
          uses: ramsey/composer-install@v1
          
      -   name: PHPStan
          run: php vendor/bin/phpstan analyze --no-progress --error-format=checkstyle | cs2pr
