on: [push]
name: Static analysis


jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-20.04
    
    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
            
      -   name: Download dependencies
          uses: ramsey/composer-install@v1
          
      -   name: PHPStan
          run: phpstan analyze --no-progress
